let numero = parseInt(prompt("digite o primeiro numero"));
let outronumero = parseInt(prompt("digite o segundo numero"));
alert(numero + outronumero);
let numero2 = parseInt(prompt("primeiro numero"));
document.write(numero2 **=2); 
let numero3 = parseInt(prompt("digite o primeiro numero"));
let outronumero3 = parseInt(prompt("digite o segundo numero"));
alert(numero3 + outronumero3);
let numero5 = parseInt(prompt("digite o primeiro numero"));
let outronumero5 = parseInt(prompt("digite o segundo numero"));
alert(numero5 - outronumero5);
let numero7 = parseInt(prompt("digite o primeiro numero"));
let outronumero7 = parseInt(prompt("digite o segundo numero"));
alert(numero7 * outronumero7);
let numero9 = parseInt(prompt("digite o primeiro numero"));
let outronumero9 = parseInt(prompt("digite o segundo numero"));
alert(numero9 / outronumero9);
let nomedeusuario = prompt("digite seu nome ");
document.write ("BemVindo, " + nomedeusuario);

